version: '3.1'

services:
  db:
    image: mysql:8.0.31
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bp1234
      MYSQL_DATABASE: gamestory

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:80"